babycheck/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('departure_form/', views.departure_form, name='departure_form'),
    path('edit_departure/edit/<int:id>/', views.edit_departure, name='edit_departure'),
    path('delete_departure/delete/<int:id>/', views.delete_departure, name='delete_departure'),
    path('read_baby_details/<int:id>/', views.read_baby_details, name='read_baby_details'),
]

first_project/urls.py
from django.contrib import admin

from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('', include('login.urls')),
    path('', include('home.urls')),
    path('', include('newsitter.urls')),
    path('', include('sitterduty.urls')),
    path('', include('babyform.urls')),
    path('', include('babycheck.urls')),
    path('', include('sales.urls')),
    path('', include('supply.urls')),
    path('', include('invent.urls')),
    path('', include('sitterlist.urls')),
    path('', include('logout.urls')),
    
    
]

home/urls.py
from . import views
from django .urls import path
urlpatterns =[
    path('', views.home_view,name='home_view'),
]

babycheck/models.py
from django.db import models
from django.utils import timezone


class Baby(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class BabyDeparture(models.Model):
    baby = models.ForeignKey(Baby, on_delete=models.CASCADE, null=True)
    baby_fetcher = models.CharField(max_length=100)
    time = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True)

    def __str__(self):
        return f"Departure of {self.baby.name}"

babycheck/forms.py
from django import forms
from .models import BabyDeparture

class BabyDepartureForm(forms.ModelForm):
    class Meta:
        model = BabyDeparture
        fields = ['baby', 'baby_fetcher', 'time', 'comment']

babycheck/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import BabyDeparture
from .forms import BabyDepartureForm




def departure_form(request):
    if request.method == 'POST':
        form = BabyDepartureForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('departure_form')
    else:
        form = BabyDepartureForm()
    
    departures = BabyDeparture.objects.all()
    return render(request, 'departure_form.html', {'form': form, 'departures': departures})


def edit_departure(request, id):
    departure = get_object_or_404(BabyDeparture, id=id)
    if request.method == 'POST':
        form = BabyDepartureForm(request.POST, request.FILES, instance=departure)
        if form.is_valid():
            form.save()
            return redirect('departure_form')
    else:
        form = BabyDepartureForm(instance=departure)
    
    return render(request, 'edit_departure.html', {'form': form})


def delete_departure(request, id):
    departure = get_object_or_404(BabyDeparture, id=id)
    if request.method == 'POST':
        departure.delete()
        return redirect('departure_form')
    
    return render(request, 'delete_departure.html', {'departure': departure})


def read_baby_details(request, id):
    departure = get_object_or_404(BabyDeparture, id=id)
    return render(request, 'baby_details.html', {'departure': departure})

babycheck/templates/baby_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baby Departure Details</title>
    {% load static %}

    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
            crossorigin="anonymous"
    />
    <title style="color: black">BABY DEPARTURE FORM</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

    <link
            href="https://fonts.googleapis.com/css?family=Raleway"
            rel="stylesheet"
    />

    <link
            href="https://fonts.googleapis.com/css?family=Montserrat"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; 
            
        }
        .form-container {
            text-align: center;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            border: 2px solid #f5c7dc;
            box-shadow: 0 0 0 0.25rem rgba(245, 199, 220, 0.25); 
    
        }
        .form-container .image {
            border-radius: 50%;
            width: 30%; 
        }
        
body {
    font-family: 'Montserrat', sans-serif;
    background-color: #f5f5f5;
    margin: 0;
    padding: 0;
    overflow-y: hidden;
}

.navbar {
    background-color: #5de0e6;
    position: fixed;
    top: 0;
    width: 100%;
    height: 100px;
    z-index: 1;
}

.navbar-brand img {
    width: 80px;
    height: 80px;
    border-radius: 50%;
    margin-left: 10px;
}

.navbar-brand h1 {
    font-size: 28px;
    color: #1a1a1a;
    margin-top: 25px;
}

.navbar-toggler-icon {
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link {
    font-weight: bold;
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link:hover {
    color: #ed83b5;
}
 
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark "
    style="background-color: #5de0e6; position: fixed; top: 0; width: 100%;  height: 100px; z-index: 1;">
   <a class="navbar-brand" href="">
       <img src="{% static 'images/daystarlogo.png' %}" alt="logo" class="logo-img">
   </a>
   <a class="nav-link" href=""><h1 class="navbar-brand" style="font-size: 25px; color: black;">BABY DEPARTURE FORM</h1></a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
           aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="nav navbar-nav ml-auto">
           {% if user.is_authenticated %}
               <li class="nav-item">
                   <a style="font-weight: bolder;  color: black;" class="nav-link" href="{% url 'departure_form' %}">GO BACK</a>
               </li>
               
               <li class="nav-item">
                <a  style="font-weight: bolder;  color: black;"class="nav-link" href="{% url 'logout'%}">LOGOUT</a>
                
              </li>

           {% endif %}
       </ul>
   </div>
</nav><br><br>
    <div class="container">
        <div class="form-container">
            <h2>More baby Details</h2>
            <img src="{% static 'images/daystarlogo.png' %}" alt="Description of the image" class="image">
            <p>Baby Fetcher: {{ departure.baby_fetcher }}</p>
            <p>Time: {{ departure.time }}</p>
            <p>Comment: {{ departure.comment }}</p>
        </div>
    </div>

    <footer class="mt-auto mb-4" style="background-color: #5de0e6; padding: 30px;">
        <div class="text-center">
            <span>Copyright &copy; <script>document.write(new Date().getFullYear())</script> DayStar DayCare</span>
        </div>
    </footer>
</body>
</html>

babycheck/templates/delete_departure.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ departure.baby_name }}"?</p>
    <button type="submit">Delete</button>
</form>

babycheck/templates/departure_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baby Departure Form</title>
    {% load static %}
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
            crossorigin="anonymous"
    />
    <title style="color: black">BABY DEPARTURE FORM</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

    <link
            href="https://fonts.googleapis.com/css?family=Raleway"
            rel="stylesheet"
    />

    <link
            href="https://fonts.googleapis.com/css?family=Montserrat"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
       


body {
    font-family: 'Montserrat', sans-serif;
    background-color: #f5f5f5;
    margin: 0;
    padding: 0;
}

.navbar {
    background-color: #5de0e6;
    position: fixed;
    top: 0;
    width: 100%;
    height: 100px;
    z-index: 1;
}

.navbar-brand img {
    width: 80px;
    height: 80px;
    border-radius: 50%;
    margin-left: 10px;
}

.navbar-brand h1 {
    font-size: 28px;
    color: #1a1a1a;
    margin-top: 25px;
}

.navbar-toggler-icon {
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link {
    font-weight: bold;
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link:hover {
    color: #ed83b5;
}


    .logo-img{
        width: 100px;
        height: 100px;
        border-radius: 50%;
        margin-left: 10px;
      }
      .container {
            display: flex;
            justify-content: space-around;
        }

        .form-container, .details-container {
            flex: 1;
            padding: 20px;
        }

        .form-input-container {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }

        .baby-list {
            display: flex;
            flex-wrap: wrap;
        }

        .baby-list-item {
            width: 300px;
            margin: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        .baby-list-item img {
            width: 100px;
            height: 100px;
            border-radius: 50%; 
            margin-right: 10px;
        }

        .baby-details {
            flex: 1;
        }

        
        .edit-button,
        .delete-button,
        .read-button {
            background-color: #ed83b5;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 5px 10px;
            margin-top: 5px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
        }

        input[type="text"],
        input[type="datetime-local"],
        textarea input[type="text"], textarea, select {
            width: 100%;
            padding: 10px;
            border: 2px solid #f5c7dc;
            box-shadow: 0 0 0 0.25rem rgba(245, 199, 220, 0.25); 
    
            border-radius: 5px;
            font-size: 16px;
        }
           

        button[type="submit"] {
            background-color: #ed83b5;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
        }

        .image-upload-input {
            display: none;
        }

        .image-upload-label {
            background-color: #ed83b5;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 8px 15px;
            cursor: pointer;
            margin-bottom: 10px;
            display: inline-block;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark "
     style="background-color: #5de0e6; position: fixed; top: 0; width: 100%;  height: 100px; z-index: 1;">
    <a class="navbar-brand" href="">
        <img src="{% static 'images/daystarlogo.png' %}" alt="logo" class="logo-img">
    </a>
    <a class="nav-link" href=""><h1 class="navbar-brand" style="font-size: 25px; color: black;">DOLL STORE PAYMENTS</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a style="font-weight: bolder;  color: black;" class="nav-link" href="{% url 'index_view' %}">HOME</a>
                </li>
                

                <li class="nav-item">
                    <a  style="font-weight: bolder;  color: black;"class="nav-link" href="{% url 'logout'%}">LOGOUT</a>
                    
                  </li>
            {% endif %}
        </ul>
    </div>
</nav><br><br><br><br><br><br>
    <div class="container">
        <div class="form-container">
            <div class="form-input-container">
                <form method="post" enctype="multipart/form-data" class="baby-form">
                    {% csrf_token %}
                    <div class="form-input-item">
                        <label for="id_baby">Baby:</label>
                        {{ form.baby }}
                    </div>
                    <div class="form-input-item">
                        <label for="id_baby_fetcher">Baby Fetcher:</label>
                        {{ form.baby_fetcher }}
                    </div>
                    <div class="form-input-item">
                        <label for="id_time">Time:</label>
                        {{ form.time }}
                    </div>
                    <div class="form-input-item">
                        <label for="id_comment">Comment:</label>
                        {{ form.comment }}
                    </div>
                    
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
        <div class="details-container">
            <div class="container baby-list">
                {% for departure in departures %}
                <div class="baby-list-item">
                    
                    <div class="baby-details">
                        <p>Baby Name: {{ departure.baby_name }}</p>
                        <a href="{% url 'edit_departure' departure.id %}" class="edit-button">Edit</a>
                        <a href="{% url 'delete_departure' departure.id %}" class="delete-button">Delete</a>
                        <a href="{% url 'read_baby_details' departure.id %}" class="read-button">Read</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <footer class="mt-auto mb-4" style="background-color: #5de0e6; padding: 30px;">
        <div class="text-center">
            <span>Copyright &copy; <script>document.write(new Date().getFullYear())</script> DayStar DayCare</span>
        </div>
    </footer>
</body>
</html>

babycheck/templates/edit_departure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Baby Departure</title>

    {% load static %}
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
            crossorigin="anonymous"
    />
    <title style="color: black">BABY DEPARTURE FORM</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

    <link
            href="https://fonts.googleapis.com/css?family=Raleway"
            rel="stylesheet"
    />

    <link
            href="https://fonts.googleapis.com/css?family=Montserrat"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <style>
        .container {
            display: flex;
            justify-content: space-around;
        }

        .form-container, .details-container {
            flex: 1;
            padding: 20px;
            max-width: 600px;
        }

        .form-input-container {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }

        .baby-list {
            display: flex;
            flex-wrap: wrap;
        }

        .baby-list-item {
            width: 300px;
            margin: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        .baby-list-item img {
            width: 100px;
            height: 100px;
            border-radius: 50%; 
            margin-right: 10px;
        }

        .baby-details {
            flex: 1;
        }

        .edit-button,
        .delete-button,
        .read-button {
            background-color: #ed83b5;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 5px 10px;
            margin-top: 5px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
        }

        input[type="text"],
        input[type="datetime-local"],
        textarea {
            border: 1px solid #ed83b5;
            border-radius: 5px;
            padding: 8px;
            margin-bottom: 10px;
            width: calc(100% - 22px); 
            box-sizing: border-box;
            border: 2px solid #f5c7dc;
            box-shadow: 0 0 0 0.25rem rgba(245, 199, 220, 0.25); 
        }

        button[type="submit"] {
            background-color: #ed83b5;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
        }
        
body {
    font-family: 'Montserrat', sans-serif;
    background-color: #f5f5f5;
    margin: 0;
    padding: 0;
}

.navbar {
    background-color: #5de0e6;
    position: fixed;
    top: 0;
    width: 100%;
    height: 100px;
    z-index: 1;
}

.navbar-brand img {
    width: 80px;
    height: 80px;
    border-radius: 50%;
    margin-left: 10px;
}

.navbar-brand h1 {
    font-size: 28px;
    color: #1a1a1a;
    margin-top: 25px;
}

.navbar-toggler-icon {
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link {
    font-weight: bold;
    color: #1a1a1a;
}

.navbar-nav .nav-item .nav-link:hover {
    color: #ed83b5;
}


    .logo-img{
        width: 100px;
        height: 100px;
        border-radius: 50%;
        margin-left: 10px;
      }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark "
     style="background-color: #5de0e6; position: fixed; top: 0; width: 100%;  height: 100px; z-index: 1;">
    <a class="navbar-brand" href="">
        <img src="{% static 'images/daystarlogo.png' %}" alt="logo" class="logo-img">
    </a>
    <a class="nav-link" href=""><h1 class="navbar-brand" style="font-size: 25px; color: black;">DOLL STORE PAYMENTS</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a style="font-weight: bolder;  color: black;" class="nav-link" href="{% url 'departure_form' %}">GO BACK</a>
                </li>
                
                <li class="nav-item">
                    <a  style="font-weight: bolder;  color: black;"class="nav-link" href="{% url 'logout'%}">LOGOUT</a>
                    
                  </li>

            {% endif %}
        </ul>
    </div>
</nav><br><br><br><br><br><br>

    <div class="container">
        <div class="form-container">
            <div class="form-input-container">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>

    <footer class="mt-auto mb-4" style="background-color: #5de0e6; padding: 30px;">
        <div class="text-center">
            <span>Copyright &copy; <script>document.write(new Date().getFullYear())</script> DayStar DayCare</span>
        </div>
    </footer>

</body>
</html>